name: Python Lambda Deploy

on :
  push:
    paths:
      - 'lambda.py'
    branches:
      - test
jobs:

#if merged to main do zip the python
  lambda-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: zip the python file lambda.py
        run: zip lambda.zip lambda.py
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # checking the directory
      - name: Check directory
        run: ls -la

      - name: Change directory to Terraform workspace
        run: cd ./

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./
      
      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./

  